### ISSUE TITLE
train

### ISSUE THREAD

**Issue by cheun726** [HarukiYqM/Non-Local-Sparse-Attention#12]

**Comment by cheun726** [comment]
Why did this happen when I tested the model I trained myself
![2](https://user-images.githubusercontent.com/72805517/132795605-6575af25-b763-4da5-8211-8f7a22a3f70e.gif)

**Comment by HarukiYqM** [comment]
Hi, your data path is correctly. Please refer to the previous issue #1

**Comment by cheun726** [comment]
I've solved the problem。


because‘--dir_data’ cannot contain 'benchmark'



thank you.you are so nice





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月10日(星期五) 下午2:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HarukiYqM/Non-Local-Sparse-Attention] train (#12)





 
Hi, your data path is correctly. Please refer to the previous issue #1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cheun726** [comment]
If I finish my training, I choose the model with the best validation results or the last model and use it to test




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月10日(星期五) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HarukiYqM/Non-Local-Sparse-Attention] train (#12)





 
Closed #12.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
