### ISSUE TITLE
Issue about the Evaluation Metrics

### ISSUE THREAD

**Issue by workingcoder** [HarukiYqM/Non-Local-Sparse-Attention#14]
First of all, thank the author for providing the code. 
I noticed that PSNR and SSIM were used as metrics in the experiments of the paper. However, only the calculation function of PSNR is offered in the code (calc_psnr func in utility.py). Calculating SSIM involves setting some parameters, which are not explained in detail in the paper or this git repository. In order to be consistent with the calculation process of your paper, can you provide the function to calculate SSIM (the cal_ssim function)? 
Thanks for your kind attention and look forward your prompt reply.

**Comment by HarukiYqM** [comment]
You can use this script for SSIM. https://github.com/yulunzhang/RCAN/blob/master/RCAN_TestCode/Evaluate_PSNR_SSIM.m

**Comment by workingcoder** [comment]
Ok, thank you. I'll try this.
