### ISSUE TITLE
Issue about the args.test_every

### ISSUE THREAD

**Issue by workingcoder** [HarukiYqM/Non-Local-Sparse-Attention#16]
I noticed that the args.test_every in the code is used to indirectly control the number of times the dataset is reused in each epoch (the repeat in SRData class).  It affects the total number of iterations. In order to reproduce the result of your paper, I want to know the value set for args.test_every in your experiments.
Thank you again and look forward to your reply.

**Comment by HarukiYqM** [comment]
Hi, the epoch in super-resolution is defined differently. Most methods starting from EDSR and based on EDSR code base (RCAN, RDN, OISR, CSNLN, SAN etc) typically follow this rule i.e. batch size 16 and test_every 1000 is a epoch.

**Comment by workingcoder** [comment]
Well, in this configuration, the training will take a long time. I will explore a more efficient training strategy.
Thank you for your reply. (^-^)
