### ISSUE TITLE
论文简单来说就是Non-local Neural Networks中的NLA+Reformer中的LSH attention?

### ISSUE THREAD

**Issue by nullxjx** [HarukiYqM/Non-Local-Sparse-Attention#19]
看了一下论文，主要创新点其实是结合了NLA（Non-local Neural Networks）思路和Reformer中的LSH attention（Locality sensitive hashing attention），所以其实只是做了一个A+B的工作，并且把它应用到超分领域，不知道我的理解对不对。

**Comment by HarukiYqM** [comment]
你理解的基本没错，最主要的motivation的确来自language model里提出的LSH，通过与NLA结合，成功摆脱了超分中NLRN里固定滑动窗口的NLA模式，改进了之前估计attention map不准确的缺点，并且得到了state-of-the-art的结果。
