### ISSUE TITLE
Mean of query in the paper

### ISSUE THREAD

**Issue by jhcha08** [HarukiYqM/Non-Local-Sparse-Attention#26]
Hello. Thanks for your great work.

I have a question on your paper.

I can't know about the exact mean of "query pixel" or "query signal" or "query location", etc.

I know that the "query" expression is indirectly derived from self-attention, but I'm not sure exactly what it means in the paper.

When I googled the query, the result is "a set of vectors you want to calculate attention for." 

Is the expression used in this and the paper similar? Then how should this be interpreted for the paper?

Thank you for reading.

**Comment by HarukiYqM** [comment]
Yes. That is what this word mean.
