### ISSUE TITLE
The number of NLSN operations?

### ISSUE THREAD

**Issue by chenquan-hdu** [HarukiYqM/Non-Local-Sparse-Attention#5]
Hi,
I set res_block=32, so the model should contain 5 NLSA modules. When I send an image to the model, it should go through 5 NLSA runs, but when I counted the NLSA runs, I found that the NLSA runs 20 times. Why?   
For each image, run the model 4 times to calculate the average PSNR?

Thank you.

**Comment by HarukiYqM** [comment]
Because the —chop flag splits the images into four parts to handle large size input. This is a widely used strategy in image super-resolution algorithms.

**Comment by chenquan-hdu** [comment]
Thank you for your help
