### ISSUE TITLE
Which parameter should be set to continue training after a break in training？

### ISSUE THREAD

**Issue by cheun726** [HarukiYqM/Non-Local-Sparse-Attention#8]
I stop training，Which parameter should I set to resume training from where I left off

**Comment by HarukiYqM** [comment]
—resume and you may have to manually adjust the epoch number and learning rate.

**Comment by cheun726** [comment]
'--resume'    Is this one？How do I set the value of this parameter and learning rate?Can you be more specific? Thank you

**Comment by HarukiYqM** [comment]
for example if you want train 100 epoch with learning rate 1e-4 for first 50 and 5e-5 for rest. Suppose you training stop at 53. To resume, please add —resume 53 and change —epoch from 100 to 47 and—let to 5e-5.

**Comment by cheun726** [comment]
thank  you  so much

**Comment by cheun726** [comment]
thank  you  so much

**Comment by cheun726** [comment]
How do I set the value of --resume to model_latest?as shown below
<img width="927" alt="2" src="https://user-images.githubusercontent.com/72805517/130546886-c5767bef-bf83-443a-ab41-35ec8dec029b.png">

**Comment by cheun726** [comment]
Why should the parameter of --data_range be set to 801-900 during test? as shown below
<img width="478" alt="3" src="https://user-images.githubusercontent.com/72805517/130549970-e99effb3-c0d3-420c-8744-88cd9826ecff.png">

**Comment by HarukiYqM** [comment]
To recover from the latest checkpoint, you have to set —resume to the the latest epoch number. 

This parameter does nothing in testing with benchmarks. Free feel to remove.

**Comment by cheun726** [comment]
thank you very much

**Comment by cheun726** [comment]
During training, why did the model with fewer parameters prompt that the GPU's memory was insufficient, but the model with more parameters did not  ？as shown below
<img width="748" alt="屏幕截图 2021-08-25 164802" src="https://user-images.githubusercontent.com/72805517/130759239-460ed91a-2a87-4b0b-95fb-4de782399cd7.png">

**Comment by cheun726** [comment]
hi,Is there any code in the program to compute FLOPS?thanks
