### ISSUE TITLE
My GPU has a small memory

### ISSUE THREAD

**Issue by cheun726** [HarukiYqM/Non-Local-Sparse-Attention#9]
How to clear video memory during training without affecting training

**Comment by HarukiYqM** [comment]
I am not sure about how to clear the memory and what video memory refer to. Since this code is fully based on EDSR (https://github.com/sanghyun-son/EDSR-PyTorch), you may want to look at that repo about how to use this code.

**Comment by cheun726** [comment]
video memory  refers to GPU's memory
